<template>
  <Page title="About Us" name="about">
      <h1>Ting Global: AI-Powered Education</h1>
      <br>
      <h3>
<p>Ting Global is a gamified educational platform that provides online courses generated and assisted by AI with partnership of the users themselves and being practiced using various social platforms including our own Ting Tank chat. Ting global is a DAO platform whereas life-long-learners are active participants and partners. The courses design including topic, name, images, videos, tasks and other, are generated by the AI in accordance to relevancy and popularity The courses are being constantly modified, improved and adjusted to each target audience using crowd wisdom and feedback systems. The courses include study groups, think tank groups and tools for better learners engagement and participation.The system studies, measures and monitors each participants' advancement, topics of interests, levels of understanding and involvement, and provides a personalized experience and feedback for an advanced and more efficient learning process.</p>
      </h3>
      <br>
      <h1>Who:</h1>
      <br>
      <h3>
<p>Ting Global is an innovative educational platform that targets a diverse range of learners, from students seeking traditional coursework to lifelong learners interested in expanding their knowledge and skills. It is open to individuals of all ages and backgrounds, making education accessible to a global audience.</p>
      </h3>      
      <br>    
      <h1>What:</h1>
      <br>
      <h3>
<p>Ting Global is a gamified decentralized autonomous organization (DAO) platform that combines the power of artificial intelligence (AI) and crowd wisdom to provide online courses. These courses cover a wide array of subjects and are generated by AI algorithms, which ensure relevancy and popularity. The platform actively involves learners as partners and active participants in their educational journey.</p>
      </h3>
      <br>
      <h1>Where:</h1>
      <br>
      <h3>
      <p>Ting Global is an online platform, accessible from anywhere in the world with an internet connection. The courses and interactions take place through integration among various social media platforms, making it convenient and accessible to a global audience.</p>
      </h3>
      <br>
      <h1>When:</h1>
      <br>
      <h3>
      <p>Ting Global operates on a continuous and dynamic schedule. Courses are constantly modified, improved, and adjusted to meet the evolving needs and preferences of learners. The platform is available 24/7, allowing learners to access content and engage with their peers at their convenience.</p>
      </h3>
      <br>
      <h1>Why:</h1>
      <br>
      <h3>
      <p>Ting Global aims to address several key challenges in the field of education, including outdated course content, lack of personalization, and limited student engagement. By utilizing AI to generate courses, encouraging active learning participation, and offering personalized learning experiences, Ting Global seeks to enhance the quality of online education and make it more accessible to learners around the world.</p>
      </h3>
      <br>
      <h1>Vision:</h1>
      <br>
      <h3>
      <p>To help learners and communities spread great practice and stories about beneficial AGI, permaculture, Regenerative communities, new economy and related topics, by bringing AI advisory & digital currency rewards into the group, and gamifying the practice. Awarding NFT prizes and other (physical goods, emotional and spiritual rewards and awards).</p>
      </h3>
      <br>
<!-- <TeamSection v-for="team in teams" :key="team.title" v-bind="team" />
    <OurCompany /> -->
    <!-- <WhyChallenge18 /> -->

    <Partners />
  </Page>
</template>

<script>
export default {
  head: {
    meta: [
      {
        hid: "description",
        name: "description",
        content:
          "Ting Global is the international body that conducts the 18 official pre-tournament challenge competitions, and the tournament. 18 days of assignments that raise awareness of sustainability and leadership issues."
      }
    ]
  },
  data() {
    return {
      teams: require("~/assets/data/teams")
    };
  }
};
</script>

<style lang="scss">
.about > section:not(.team-section) {
  .section-heading-wrapper {
    margin-bottom: 5rem;

    @include respond(mobile) {
      margin-bottom: 3.5rem;
    }
  }
}
</style>
